version: "3"

volumes:
  postgres_data:
      driver: local

services:
  nginx:
    image: nginx:latest
    depends_on:
      usetech:
        condition: service_started
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - default
      - public

  postgres:
      image: postgres
      restart: on-failure
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: pass
      networks:
        - default

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    restart: on-failure
    depends_on:
      postgres:
        condition: service_started
    command:
      - start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_SCHEMA=public
      - KC_DB_PASSWORD=pass
    ports:
      - "8080:8080"
    networks:
      - default
      - public

  usetech:
    build: .
    restart: on-failure
    expose:
      - "8000"
    depends_on:
      keycloak:
        condition: service_started
    networks:
      - default

networks:
    default:
      internal: true
    public:
      internal: false